# Generated by Django 5.0.7 on 2024-07-27 12:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('license_plate_number', models.CharField(max_length=15, unique=True)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=50)),
                ('mileage', models.IntegerField()),
                ('fuel_tank_capacity', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_trip', models.CharField(blank=True, max_length=255)),
                ('obdii_fault_codes', models.TextField(blank=True)),
                ('fuel_level', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('rpm_of_engine', models.FloatField(blank=True, null=True)),
                ('engine_temperature', models.FloatField(blank=True, null=True)),
                ('engine_load', models.FloatField(blank=True, null=True)),
                ('live_fuel_usage', models.FloatField(blank=True, null=True)),
                ('gps_data', models.CharField(blank=True, max_length=255)),
                ('assign_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset')),
                ('assign_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.driver')),
            ],
        ),
    ]
