# Generated by Django 5.0.7 on 2024-07-27 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_asset_assign_driver_remove_asset_assign_truck_and_more'),
        ('drivers', '0003_remove_driver_assign_vehicle_and_more'),
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='assign_asset',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='assign_driver',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='license_plate_number',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='rpm_of_engine',
        ),
        migrations.AddField(
            model_name='truck',
            name='asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_truck_asset', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='truck',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_truck', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='truck',
            name='license_plate',
            field=models.CharField(default='UNKNOWN', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='rpm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='engine_load',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='engine_temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='fuel_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='fuel_tank_capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='truck',
            name='gps_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='last_trip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='make',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='truck',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='truck',
            name='obdii_fault_codes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='vin',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
