# Generated by Django 5.0.7 on 2024-07-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0003_truck_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
