# Generated by Django 5.0.7 on 2024-07-27 12:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('license_plate_number', models.CharField(max_length=15, unique=True)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('max_weight_capacity', models.FloatField()),
                ('length', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gps', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
