# Generated by Django 5.0.7 on 2024-07-27 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
        ('drivers', '0002_initial'),
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='assign_driver',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='assign_truck',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='gps',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='license_plate_number',
        ),
        migrations.AddField(
            model_name='asset',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_asset_truck', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='asset',
            name='gps_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='license_plate',
            field=models.CharField(default='UNKNOWN', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='truck',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_asset', to='trucks.truck'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='asset',
            name='make',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='max_weight_capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='asset',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='vin',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
